# Generated by Django 5.2.1 on 2025-06-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_sessions', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.CharField(default='Зал 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='language',
            field=models.CharField(choices=[('original', 'Оригинал'), ('dubbed', 'Дублированный')], max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
