# Generated by Django 5.2.1 on 2025-06-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_sessions', '0002_session_hall_alter_session_date_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={},
        ),
    ]
