# Generated by Django 5.2.1 on 2025-06-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_sessions', '0003_alter_session_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.CharField(default='Зал 1', max_length=50),
        ),
    ]
