# Generated by Django 5.2.1 on 2025-06-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('duration', models.IntegerField(verbose_name='Продолжительность (минуты)')),
                ('age_rating', models.CharField(max_length=10, verbose_name='Возрастной рейтинг')),
                ('is_coming_soon', models.BooleanField(default=False, verbose_name='Скоро в кино')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('trailer_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на трейлер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
